
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'telegram-bot-ruby'
gem 'dotenv-rails', groups: [:development, :test]

gem 'mechanize', '~> 2.7', '>= 2.7.5'
gem 'json', '~> 2.1'
gem 'yandex-translator'
